[[plugins]]
  package = "@netlify/plugin-nextjs"

[build]
command = "npm run build"
ublish = ".next"

[[headers]]
  for = "/_next/image/*"

[headers.values]
    Strict-Transport-Security = "max-age=31536000"
    X-Test = 'foobar'